### ISSUE TITLE
Deleting a feature flag does not disable functionality

### ISSUE THREAD

**Issue by spookymattress** [thetanz/featureflags-al#1] opened 2021-05-31 12:31 UTC
I have created a feature flag called "MyFeat" and enabled it. Works fine!

When I delete the feature flag, the functionality is still active. Shouldn't it be disabled? Or what is the intended behaviour?

**Comment by vody** [comment] 2021-05-31 21:01
@spookymattress, looks like that app recalculates a flag only if you manually delete a condition:
https://github.com/thetanz/featureflags-al/blob/5b34891c5f2e88e5bdf20633efe10ea5b1d2be3b/MAIN/src/table/FeatureFlag.Table.al#L78 
https://github.com/thetanz/featureflags-al/blob/5b34891c5f2e88e5bdf20633efe10ea5b1d2be3b/MAIN/src/codeunit/FeatureFlagMgt.Codeunit.al#L139
Thank you for this feedback. Will work out a fix for this.

**Comment by vody** [comment] 2021-05-31 23:42
@spookymattress, could you please validate a latest version, so will close as confirmed.

**Closed as completed** 2021-06-14 22:55 UTC
Labels: 🐛 bug
